### ISSUE TITLE
ImportError: cannot import name QgsCodeEditorHTML

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-plugin#106]
Unsure whether this is an issue of LM plugin. I just recompiled QGIS 2.18 on Debian Sid, and at startup I get:
```
Traceback (most recent call last):
  File "/usr/local/src/qgis/QGIS/build_qgis2/output/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/pcav/.qgis2/python/plugins/lizmap/__init__.py", line 75, in classFactory
    from lizmap import lizmap
  File "/usr/local/src/qgis/QGIS/build_qgis2/output/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/pcav/.qgis2/python/plugins/lizmap/lizmap.py", line 78, in 
    from lizmapdialog import lizmapDialog
  File "/usr/local/src/qgis/QGIS/build_qgis2/output/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/pcav/.qgis2/python/plugins/lizmap/lizmapdialog.py", line 52, in 
    os.path.dirname(__file__), 'ui_lizmap.ui'))
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 211, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 2483, in 
ImportError: cannot import name QgsCodeEditorHTML
```

**Comment by pcav** [comment]
Duplicate
