### ISSUE TITLE
Error when saving cfg

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-plugin#133]
```
 WARNING    Traceback (most recent call last):
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/lizmap.py", line 2562, in getMapOptions
              self.writeProjectConfigFile()
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/lizmap.py", line 2274, in writeProjectConfigFile
              lExtent.yMaximum()
              File "", line 1, in 
             NameError: name 'inf' is not defined
```

**Comment by pcav** [comment]
It turned out being an error in data. Sorry for the noise.
