### ISSUE TITLE
AttributeError when using the drag&drop form popup

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-plugin#190]
## Description

```bash
Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'str' object has no attribute 'items' 
Traceback (most recent call last):
  File "C:/Users/nicolasm/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\lizmap.py", line 2102, in setTooltipContentFromForm
    htmlcontent = self.createPopupNodeItemFromForm(layer, root, 0, [], '')
  File "C:/Users/nicolasm/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\lizmap.py", line 2051, in createPopupNodeItemFromForm
    h = self.createPopupNodeItemFromForm(layer, n, level, headers, html)
  File "C:/Users/nicolasm/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\lizmap.py", line 1974, in createPopupNodeItemFromForm
    m.append(['%s=>%s' % (v.replace("'", "’"), k.replace("'", "’")) for k, v in d.items()][0])
AttributeError: 'str' object has no attribute 'items'
```

The remote debugger screenshot to see the content of variables:

![bug](https://user-images.githubusercontent.com/1609292/72062697-97d70f80-32d8-11ea-8680-174d2a69dea0.jpg)

The error happened on every Valuemap field. We removed one ValueMap field from the drag and drop and the error was on the next ValueMap field.

## Context
* QGIS version: 3.4 ?
* Lizmap version: The latest while doing a training : 3.1.7
* OS: Windows

**Comment by Gustry** [comment]
Fixed in 3.2.9
https://github.com/3liz/lizmap-plugin/commit/6486a9512b678edf5bd0a8e0cc28e085707eebaa
