### ISSUE TITLE
couldn't load plugin on qgis desktop 3.4.15

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#206]
hi,

i'm trying to install the master branch on gis desktop 3.4.15 and i got these logs:

```
Couldn't load plugin 'lizmap-plugin-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'lizmap-plugin-master.qgis_plugin_tools' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap-plugin-master\__init__.py", line 51, in classFactory
    from .lizmap import Lizmap
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap-plugin-master\lizmap.py", line 88, in 
    from .definitions.atlas import AtlasDefinitions
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap-plugin-master\definitions\atlas.py", line 4, in 
    from ..qgis_plugin_tools.tools.i18n import tr
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'lizmap-plugin-master.qgis_plugin_tools'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.15-Madeira Madeira, e83d02e274 

Python Path:
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.4\apps\gdal2\pymod3\scripts
C:\PROGRA~1\QGIS3~1.4\apps\gdal2\pymod3\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\Scripts
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```
thanks

**Comment by Gustry** [comment]
How did you get the source code on github, from the ZIP or from git ?

**Comment by Gustry** [comment]
I see `lizmap-plugin-master`, so it means from the ZIP. It's not possible to use the ZIP provided by GitHub.

If you want the zip, you must use the link provided here : https://github.com/3liz/lizmap-plugin/blob/master/README.md

**Comment by josemvm** [comment]
@Gustry thanks for the readme update too
