### ISSUE TITLE
Set tooltip content from form: In createPopupNodeItemFromForm 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-plugin#227]
## Description
```
AttributeError: 'str' object has no attribute 'items'
Traceback (most recent call last):
File "C:/Users/s.audrain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\lizmap.py", line 1820, in setTooltipContentFromForm
htmlcontent = self.createPopupNodeItemFromForm(layer, root, 0, [], '')
File "C:/Users/s.audrain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\lizmap.py", line 1769, in createPopupNodeItemFromForm
h = self.createPopupNodeItemFromForm(layer, n, level, headers, html)
File "C:/Users/s.audrain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\lizmap.py", line 1769, in createPopupNodeItemFromForm
h = self.createPopupNodeItemFromForm(layer, n, level, headers, html)
File "C:/Users/s.audrain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\lizmap.py", line 1692, in createPopupNodeItemFromForm
m.append(['%s=>%s' % (v.replace("'", "’"), k.replace("'", "’")) for k, v in d.items()][0])
AttributeError: 'str' object has no attribute 'items'
```

## Context
* QGIS version: 3.4
* Lizmap version: 3.2
* OS: Windows

**Comment by Gustry** [comment]
Duplicate https://github.com/3liz/lizmap-plugin/issues/190
