### ISSUE TITLE
maptip_from_form: relation.referencedLayer() can be None

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-plugin#287]
## Description

The relation reference widget has not been well configured. The relation has not been set because a style has been applied to the layer and the relations has not been discovered before.

```
 AttributeError: 'NoneType' object has no attribute 'displayExpression'

Traceback (most recent call last):
  File "C:/Users/FSEISSON.AGGLOTDP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 1558, in maptip_from_form
    html_content = Tooltip.create_popup_node_item_from_form(layer, root, 0, [], '', relation_manager)
  File "C:/Users/FSEISSON.AGGLOTDP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\tooltip.py", line 120, in create_popup_node_item_from_form
    h = Tooltip.create_popup_node_item_from_form(layer, n, level, headers, html, relation_manager)
  File "C:/Users/FSEISSON.AGGLOTDP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\tooltip.py", line 120, in create_popup_node_item_from_form
    h = Tooltip.create_popup_node_item_from_form(layer, n, level, headers, html, relation_manager)
  File "C:/Users/FSEISSON.AGGLOTDP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\tooltip.py", line 120, in create_popup_node_item_from_form
    h = Tooltip.create_popup_node_item_from_form(layer, n, level, headers, html, relation_manager)
  File "C:/Users/FSEISSON.AGGLOTDP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\tooltip.py", line 70, in create_popup_node_item_from_form
    display = relation.referencedLayer().displayExpression()
AttributeError: 'NoneType' object has no attribute 'displayExpression'
```

## Context
* QGIS version: 3.10.6
* Lizmap version: 3.2.16
* OS: Windows

**Comment by Gustry** [comment]
Fixed in 442c464163c85161e5482e94459154449dc01077
