### ISSUE TITLE
Unable to use plugin with QGIS 2.4 64 bits - Python Error

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/lizmap-plugin#29]
LizMap Plugin 1.9.8
openSUSE 12.3 64 bits
QGIS 2.4 64 bits

When open a project, launch lizmap, got these errors lines when i click on save : 

```
Traceback (most recent call last):
  File "/home/n.rochard/.qgis2/python/plugins/lizmap/lizmap.py", line 2120, in getMapOptions
    self.writeProjectConfigFile()
  File "/home/n.rochard/.qgis2/python/plugins/lizmap/lizmap.py", line 1626, in writeProjectConfigFile
    r = QgsMapRenderer()
TypeError: C++ type 'const QgsMapLayer*' is not supported as  type
```
```
Version de Python :
2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]

Version de QGIS :
2.4.0-Chugiak Chugiak, exported
```

and after, got these errors when I tunr off this error window : 

```
Traceback (most recent call last):
  File "/home/n.rochard/.qgis2/python/plugins/lizmap/lizmap.py", line 2492, in warnOnClose
    self.writeProjectConfigFile()
  File "/home/n.rochard/.qgis2/python/plugins/lizmap/lizmap.py", line 1626, in writeProjectConfigFile
    r = QgsMapRenderer()
TypeError: C++ type 'const QgsMapLayer*' is not supported as  type
```
```
Version de Python :
2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]

Version de QGIS :
2.4.0-Chugiak Chugiak, exported
```

**Comment by Gustry** [comment]
Closing as this line doesn't exist anymore in the plugin. Feel free to reopen another issue.
