### ISSUE TITLE
Python exception when removing a layer

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-plugin#300]
## Description

Not easy to trigger, it's not always.
I guess when a previous CFG or removing old layer (not in the previous CFG)

```
AttributeError: 'NoneType' object has no attribute 'data' 
Traceback (most recent call last):
  File "/home/etienne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/plugin.py", line 1064, in remove_layer_from_table_by_layer_ids
    manager.layers_has_been_deleted(layer_ids)
  File "/home/etienne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/forms/table_manager.py", line 260, in layers_has_been_deleted
    value = cell.data(Qt.UserRole)
AttributeError: 'NoneType' object has no attribute 'data'
```

## Context
* QGIS version: 3.10
* Lizmap version: Master
* OS: Ubuntu

**Comment by Gustry** [comment]
I can't replicate anymore, and I think it has been fixed
