### ISSUE TITLE
Python exception for field default value on a server

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-plugin#307]
## Description

```
15:19:10 INFO wfsOutputExtension[759]: WFSFilter.requestReady
15:19:10 INFO Server[759]: FIELDS:id,name
15:19:10 INFO Server[759]: FILTER:intersects(@current_geometry, $geometry)
15:19:10 INFO Server[759]: FORM_FEATURE:{"type":"Feature","geometry":{"type":"Point","coordinates":[-149.42664658686098,-17.68931766473747]},"properties":[]}
15:19:10 INFO Server[759]: LAYER:municipalities
15:19:10 INFO Server[759]: MAP:/home/etienne/tmp/demo_qgisid/demo.qgs
15:19:10 INFO Server[759]: REQUEST:getFeatureWithFormScope
15:19:10 INFO Server[759]: SERVICE:EXPRESSION
15:19:10 CRITICAL lizmap[759]: Unhandled exception:
Traceback (most recent call last):
  File "/home/etienne/dev/qgis/server_plugin/lizmap/server/expression_service.py", line 91, in executeRequest
    elif reqparam == 'GETFEATUREWITHFORMSCOPE':
  File "/home/etienne/dev/qgis/server_plugin/lizmap/server/expression_service.py", line 657, in getFeatureWithFormScope
    response.setHeader("Content-Type", "application/json")
  File "/home/etienne/dev/qgis/server_plugin/lizmap/server/core.py", line 49, in getServerFid
  File "/home/etienne/dev/qgis/server_plugin/lizmap/server/core.py", line 49, in <listcomp>
TypeError: QgsFeature.attributes(): too many arguments

15:19:10 CRITICAL lizmap[759]: Lizmap request error Internal server error: Internal 'lizmap' service error

```

@rldhont Related to my error this morning.

## Context
* QGIS version: 3.10
* Lizmap version: LWC Master
* OS: Ubuntu 20.04

**Comment by Gustry** [comment]
Invalid I think
