### ISSUE TITLE
plugin error after updating latest version

### ISSUE THREAD

**Issue by Marcuzzo77** [3liz/lizmap-plugin#312]
## Description

Hello to all,

I have a problem updating lizmap plugin to latest version.
The previous one worked well.
The error when launching the plugin is as follows:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2130: ordinal not in range (128)
Traceback (most recent call last):
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins [packageName] = package.classFactory (iface)
  File "/ Users / solutop / Library / Application Support / QGIS / QGIS3 / profiles / default / python / plugins / lizmap / __ init__.py", line 55, in classFactory
    from lizmap.plugin import Lizmap
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import (name, globals, locals, fromlist, level)
  File "/ Users / solutop / Library / Application Support / QGIS / QGIS3 / profiles / default / python / plugins / lizmap / plugin.py", line 98, in
    from lizmap.forms.table_manager import TableManager
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import (name, globals, locals, fromlist, level)
  File "/ Users / solutop / Library / Application Support / QGIS / QGIS3 / profiles / default / python / plugins / lizmap / forms / table_manager.py", line 21, in
    LOGGER = logging.getLogger (plugin_name ())
  File "/ Users / solutop / Library / Application Support / QGIS / QGIS3 / profiles / default / python / plugins / lizmap / qgis_plugin_tools / tools / resources.py", line 37, in plugin_name
    metadata = metadata_config ()
  File "/ Users / solutop / Library / Application Support / QGIS / QGIS3 / profiles / default / python / plugins / lizmap / qgis_plugin_tools / tools / resources.py", line 50, in metadata_config
    config.read (path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 697, in read
    self._read (fp, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 1017, in _read
    for lineno, line in enumerate (fp, start = 1):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode (input, self.errors) [0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2130: ordinal not in range (128)

Python version: 3.8.5 (v3.8.5: 580fbb018f, Jul 20 2020, 12:11:27) [Clang 6.0 (clang-600.0.57)]
QGIS version: 3.14.1-Pi Pi, exported

Python path:
/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python
/ Users / solutop / Library / Application Support / QGIS / QGIS3 / profiles / default / python
/ Users / solutop / Library / Application Support / QGIS / QGIS3 / profiles / default / python / plugins
/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/F/Python/3.8
/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
/ Users / solutop / Library / Application Support / QGIS / QGIS3 / profiles / default / python
/ Users / solutop / Library / Application Support / QGIS / QGIS3 / profiles / default / python / plugins / mmqgis / forms

## Context
* QGIS version: 3.14.1-Pi
* Lizmap version: 3.4.0rc1
* OS: OSX Sierra 10.12.6

**Comment by Gustry** [comment]
Thanks for the feedback.
I need to apply : https://github.com/3liz/lizmap-plugin/commit/f0c55da0e12b5e4ae803389384937386b15d1837

You can do it your side if it's urgent.
Edit /Users/solutop/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/lizmap/qgis_plugin_tools/tools/resources.py, line 50

I will release a bugfix version this week.

Sorry for that.

**Comment by Marcuzzo77** [comment]
@Gustry thank you so much
Marco

**Comment by Gustry** [comment]
Fixed in 906424b7d8062a7ccf1bd1ebad4ef4cfa03a8480
