### ISSUE TITLE
Python error with ElementTree

### ISSUE THREAD

**Issue by AdelineF** [3liz/lizmap-plugin#40]
Hello, 

I have a problem when i open the plugin Lizmap :

```
Traceback (most recent call last):
  File "C:/Users/XXX/.qgis2/python/plugins\lizmap\lizmap.py", line 2754, in run
    self.embeddedGroups = self.getProjectEmbeddedGroup()
  File "C:/Users/XXX/.qgis2/python/plugins\lizmap\lizmap.py", line 2358, in getProjectEmbeddedGroup
    arbre = ET.parse(f)
  File "C:\PROGRA~1\QGISWI~1\apps\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\PROGRA~1\QGISWI~1\apps\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\PROGRA~1\QGISWI~1\apps\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\PROGRA~1\QGISWI~1\apps\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1870, column 31
```

```
Version de Python :
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

Version de QGIS :
2.8.2-Wien Wien, 1b929ef

Chemin vers Python : ['C:/Users/XXX/.qgis2/python/plugins\processing', 'C:\Users\XXX\.qgis2\python\plugins\GeoCoding\libs', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python', u'C:/Users/XXX/.qgis2/python', u'C:/Users/XXX/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\bin\python27.zip', 'C:\PROGRA~1\QGISWI~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISWI~1\bin', 'C:\PROGRA~1\QGISWI~1\apps\Python27', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg', u'C:/Users/XXX/.qgis2//python', 'C:\Users\XXX\.qgis2\python\plugins\mmqgis/forms', 'C:\PROGRA~1\QGISWI~1\apps\qgis\python\plugins\fTools\tools', 'C:/Users/XXX/Documents/LIZMAP']
```

Can you help us ? We don't understand !

**Comment by Gustry** [comment]
Do you still have the issue?

**Comment by Gustry** [comment]
I'm closing for lacking of feedbacks. Feel free to reopen if necessary or a new ticket.
