### ISSUE TITLE
Cannot setup Lizmap Plugin with LWC

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-plugin#468]
## Description

I have QGIS Desktop installed on Windows and Lizmap Web Client on docker. When I try to add register Lizmap Server in Lizmap Plugin an error pops up
![image](https://user-images.githubusercontent.com/1684359/212299113-5d766599-19ea-407a-80e0-90efec7f0ff5.png)

In Lizmap web client:

![image](https://user-images.githubusercontent.com/1684359/212299287-53ff8931-6157-4858-9ffb-f6c163dad3c4.png)

Log from web:

`2023/01/13 12:30:36 [error] 30#30: *144 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: pg_close(): supplied resource is not a valid PostgreSQL link resource in /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php:202

Stack trace:
#0 /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php(202): pg_close()
#1 /www/lizmap/vendor/jelix/jelix/lib/jelix/db/jDbConnection.class.php(113): pgsqlDbConnection->_disconnect()
#2 /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php(69): jDbConnection->__destruct()
#3 [internal function]: pgsqlDbConnection->__destruct()

}
  thrown in /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php on line 202" while reading upstream, client: 192.168.2.5, server: lizmap, request: "GET /admin.php/admin/logs HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "192.168.2.12:8090", referrer: "http://192.168.2.12:8090/admin.php/admin/server_information"
192.168.2.5 - - [13/Jan/2023:12:30:36 +0200] "GET /admin.php/admin/logs HTTP/1.1" 200 3067 "http://192.168.2.12:8090/admin.php/admin/server_information" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
192.168.2.5 - - [13/Jan/2023:12:30:39 +0200] "GET /admin.php/admin/server_information HTTP/1.1" 200 3489 "http://192.168.2.12:8090/admin.php/admin/logs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"`

## Context
* QGIS version: 3.22.14
* Lizmap version: 3.6.0
* OS: Windows and Ubuntu server

**Comment by Gustry** [comment]
When authenticated in your webvrowser as `lizmap` user, do you have complete JSON file when visiting : 

http://192.168.2.12:8090/index.php/view/app/metadata

You should see your QGIS server version 3.22.14 in this JSON file.

Not sure if it's a bug for LWC or for the Python plugin.

**Comment by ygorigor** [comment]
This is json:

`{"info":{"version":"3.6.0","date":"2022-12-09"},"dependencies":{"jelix":{"version":"1.8.0-rc.1","minversion":"1.8.0-rc.1","maxversion":"1.8.0-rc.1"}},"qgis_server_info":{"metadata":{"commit_id":"4cde646cf9","name":"Bia\u0142owie\u017ca","py_qgis_server":true,"py_qgis_server_version":"1.8.7rc0","tag":"final-3_22_14","version":"3.22.14","version_int":32214},"plugins":{"atlasprint":
{"commitNumber":"1","commitSha1":"7b8a3ea12775bcdcdac0b0f8432bd64adb3dc528","dateTime":"2022-10-19T08:10:14Z","name":"atlasprint","repository":"https:\/\/github.com\/3liz\/qgis-atlasprint","version":"3.3.2"},"lizmap_server":{"commitNumber":"1","commitSha1":"e12932fd4a08aab007af4fdee2c6a11d9638c578","dateTime":"2022-12-16T12:59:48Z","name":"Lizmap server","repository":"https:\/\/github.com\/3liz\/qgis-lizmap-server-plugin","version":"1.2.2"},"wfsOutputExtension":{"commitNumber":"1","commitSha1":"2cbc73252e4eb0687452875ab6e457a0fdbb8e2f","dateTime":"2022-10-05T12:38:47Z","name":"wfsOutputExtension","repository":"https:\/\/github.com\/3liz\/qgis-wfsOutputExtension","version":"1.7.1"}},"py_qgis_server":{"build_id":"202212161553","commit_id":"424902f","found":true,"stable":false,"stable_release":false,"version":"1.8.7rc0"},"services":["WMS","WFS","WCS","WMTS","ATLAS","EXPRESSION","LIZMAP"]}}`

**Comment by Gustry** [comment]
Hum ,strange.

Can you open your "development and debug panel" in QGIS, press the "red icon" to record all HTTP requests and then try to save in Lizmap your server ?

You should see the request from QGIS to your Lizmap server. It shouldn't be a red line, because the HTTP code is not a 500 error ? (server exception)

**Comment by ygorigor** [comment]
```[
  {
    "Bytes Received": 0,
    "Bytes Total": 0,
    "Cache (control)": "Always load from network, do not check cache",
    "Cache (save)": "Result cannot be stored in cache",
    "Headers": {
      "User-Agent": "Mozilla/5.0 QGIS/32214"
    },
    "ID": "src\\core\\network\\qgsnetworkcontentfetcher.cpp:40 (QgsNetworkContentFetcher::fetchContent)",
    "Initiator": "QgsNetworkContentFetcher",
    "Operation": "GET",
    "Replies": 2,
    "Reply": {
      "Cache (result)": "Used entry from cache",
      "Headers": {
        "Accept-Ranges": "bytes",
        "Access-Control-Allow-Origin": "*",
        "Cache-Control": "max-age=300",
        "Connection": "keep-alive",
        "Content-Encoding": "gzip",
        "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; sandbox",
        "Content-Type": "text/plain; charset=utf-8",
        "Date": "Fri, 13 Jan 2023 11:06:45 GMT",
        "ETag": "W/\"901a66c97d64adff82ee697d92611b3bd9cb304e6d67795a7af662c6c409b90b\"",
        "Expires": "Fri, 13 Jan 2023 11:11:45 GMT",
        "Source-Age": "0",
        "Strict-Transport-Security": "max-age=31536000",
        "Vary": "Authorization,Accept-Encoding,Origin",
        "Via": "1.1 varnish",
        "X-Cache": "HIT",
        "X-Cache-Hits": "1",
        "X-Content-Type-Options": "nosniff",
        "X-Fastly-Request-ID": "8d6283f40986fcf7e5839013ac624560f1aaf4c5",
        "X-Frame-Options": "deny",
        "X-GitHub-Request-Id": "BBEE:2E8A:3DE364:5E1DE6:63C11707",
        "X-Served-By": "cache-hhn-etou8220037-HHN",
        "X-Timer": "S1673608006.810602,VS0,VE171",
        "X-XSS-Protection": "1; mode=block"
      },
      "Status": "200"
    },
    "Thread": "0x0000017a0188ce80",
    "Total time (ms)": 1330,
    "URL": "https://raw.githubusercontent.com/3liz/lizmap-web-client/versions/versions.json"
  },
  {
    "Bytes Received": 328,
    "Bytes Total": 328,
    "Cache (control)": "Load from cache if available, otherwise load from network",
    "Cache (save)": "Can store result in cache",
    "Headers": {
      "Authorization": "Basic bGl6bWFwOmRlbW9yYWRtb24=",
      "User-Agent": "Mozilla/5.0 QGIS/32214"
    },
    "Initiator": "unknown",
    "Operation": "GET",
    "Replies": 2,
    "Reply": {
      "Cache (result)": "Read from network",
      "Error": "Error transferring http://192.168.2.12:8090/index.php/view/app/metadata - server replied: Internal Server Error",
      "Error Code": "401",
      "Headers": {
        "Cache-Control": "no-store, no-cache, must-revalidate",
        "Connection": "keep-alive",
        "Content-Type": "application/json",
        "Date": "Fri, 13 Jan 2023 11:07:37 GMT",
        "Expires": "Thu, 19 Nov 1981 08:52:00 GMT",
        "Pragma": "no-cache",
        "Server": "nginx/1.23.3",
        "Set-Cookie": "PHPSESSID=7ug1l1i9f655ndmeo49136s4is; path=/; HttpOnly",
        "Transfer-Encoding": "chunked",
        "X-Powered-By": "PHP/8.0.26"
      },
      "Status": "500"
    },
    "Thread": "0x0000017a4fa7aed0",
    "Total time (ms)": 1,
    "URL": "http://192.168.2.12:8090/index.php/view/app/metadata"
  }
]```

**Comment by Gustry** [comment]
From your result :  

>     "URL": "http://192.168.2.12:8090/index.php/view/app/metadata"

replies with 

>       "Error": "Error transferring http://192.168.2.12:8090/index.php/view/app/metadata - server replied: Internal Server Error",

While you tried this URL from your webbrowser, connected as `lizmap` : http://192.168.2.12:8090/index.php/view/app/metadata

I don't know why the result would be different from QGIS Desktop versus your webbrowser.

Empty your error log in the LWC admin panel. Still the same error when your request the URL ?

I'm transferring your issue on Lizmap Web Client.
