### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' 

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-plugin#481]
## Description

```
AttributeError: 'NoneType' object has no attribute 'get' 
Traceback (most recent call last):
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 3151, in save_cfg_file
    self.write_project_config_file()
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 2585, in write_project_config_file
    if is_lizmap_dot_com_hosting(server_metadata):
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\saas.py", line 21, in is_lizmap_dot_com_hosting
    return metadata.get('hosting', '') == 'lizmap.com'
AttributeError: 'NoneType' object has no attribute 'get'
```

## Context
* QGIS version: latest 3.28
* Lizmap version: latest from QGIS plugin repo
* OS: Windows 10

**Comment by gioman** [comment]
Had to revert to 3.10.1 as 3.11.0 gives the above error regardless of the project/data.

**Comment by Gustry** [comment]
This code has been introduced in 3.10.0 so before the version you are releasing.

Reading the changelog between 3.10.1 and 3.11.0, I don't see anything.

I suspect your were using Lizmap with a missing "signal" when it's fetching the metadata from your server.

I guess you can upgrade again and just try to check your server list, does all server as a QGIS server version ?

**Comment by gioman** [comment]
@Gustry seems you are right.

**Comment by Gustry** [comment]
Slightly improved in the coming latest bugfix 3.11.1
