### ISSUE TITLE
Unable to load lizmap-plugin on qgis (github version)

### ISSUE THREAD

**Issue by Spitfiire** [3liz/lizmap-plugin#70]
Hi,

I tried to install the new version but i got some errors : 

> Impossible de charger l'extension lizmap provoque une erreur lors de l'appel de sa méthode classFactory() 
ImportError: No module named qgscollapsiblegroupbox 
Traceback (most recent call last):
  File "D:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Administrator/.qgis2/python/plugins\lizmap\__init__.py", line 75, in classFactory
    from lizmap import lizmap
  File "D:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Administrator/.qgis2/python/plugins\lizmap\lizmap.py", line 56, in 
    from lizmapdialog import lizmapDialog
  File "D:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Administrator/.qgis2/python/plugins\lizmap\lizmapdialog.py", line 56, in 
    os.path.dirname(__file__), 'ui_lizmap.ui'))
  File "D:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 213, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 1799, in 
  File "D:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named qgscollapsiblegroupbox

Versionde Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Version de QGIS : 2.18.1 Las Palmas, 3e73840 

Can you help me ?

**Comment by josemvm** [comment]
hi @Spitfiire 

try to replace "qgscollapsiblegroupbox.h" by "qgis.gui" in ui_lizmap.ui file

**Comment by Spitfiire** [comment]
It works, thanks
