### ISSUE TITLE
Plugin broken

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-plugin#73]
Upon startup the plugin stops:
```
TypeError: write() takes exactly 2 arguments (1 given) 
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/lizmap/lizmap.py", line 2677, in run
    if not self.dlg.isVisible() and self.checkGlobalProjectOptions():
  File "/home/paolo/.qgis2/python/plugins/lizmap/lizmap.py", line 2335, in checkGlobalProjectOptions
    p.write()
TypeError: write() takes exactly 2 arguments (1 given)
```
QGIS 2.14, I believe the same happens with 2.18.
Debian.

**Comment by pcav** [comment]
Now it works, I do not know what has changed.
