### ISSUE TITLE
UnicodeEncodeError with nordic characters

### ISSUE THREAD

**Issue by ninsbl** [3liz/lizmap-plugin#76]
When I try to use layers with Norwegian characters ø/æ/å in the Lizmap plugin version 2.2.0 I get

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 0: ordinal not in range(128) 
Traceback (most recent call last):
  File "/home/stefan/.qgis2/python/plugins/lizmap/lizmap.py", line 2735, in run
    self.getConfig()
  File "/home/stefan/.qgis2/python/plugins/lizmap/lizmap.py", line 813, in getConfig
    self.loadConfigIntoTableWidget(key)
  File "/home/stefan/.qgis2/python/plugins/lizmap/lizmap.py", line 888, in loadConfigIntoTableWidget
    newItem = QTableWidgetItem(str(value))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 0: ordinal not in range(128)
`

And no layers are displayed.

With the earlier version of the plugin I got that error first when I clicked on "Save"...

**Comment by ninsbl** [comment]
Sorry, I see it is a duplicate of #71
