### ISSUE TITLE
Problem - SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by Heryx** [3liz/lizmap-plugin#85]
Hi everyone,
I've just installed Lizmap in QGis3, but I've obtained this error:

> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "lizmap dialog close")? 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "--/--/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/__init__.py", line 75, in classFactory
    from lizmap import lizmap
  File "--/--/usr/lib/python3/dist-packages/qgis/utils.py", line 666, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/lizmap.py", line 2666
    print "lizmap dialog close"
                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "lizmap dialog close")?

Thank you so much.

**Comment by mdouchin** [comment]
Indeed, Lizmap is not QGIS 3 compatible yet. I was waiting for the API freeze to do it.

**Comment by jlstanus** [comment]
#91

**Comment by Heryx** [comment]
Ok, thanks you.

**Comment by Gustry** [comment]
This should now be fixed. Feel free to reopen if the bug happens again.
