### ISSUE TITLE
AttributeError: module 'qgis.PyQt.QtGui' has no attribute 'QDialog' 

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-plugin#98]
Branch: master_3

Error stack:

```
AttributeError: module 'qgis.PyQt.QtGui' has no attribute 'QDialog' 
Traceback (most recent call last):
  File "<masked>/python/plugins/lizmap/lizmap.py", line 2122, in configurePopup
    from .lizmappopupdialog import lizmapPopupDialog
  File "/<masked>/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "<masked>/python/plugins/lizmap/lizmappopupdialog.py", line 51, in 
    class lizmapPopupDialog(QtGui.QDialog):
AttributeError: module 'qgis.PyQt.QtGui' has no attribute 'QDialog'
```

QDialog in Qt 5 is no more a members of  `qgis.PyQt.QtGui`: use  `qgis.PyQt.QtWidgets` instead.

**Comment by dmarteau** [comment]
Fixed with PR  #99
